#!/usr/bin/env bash
# Ultra-light 1x4090 full-finetune smoke launch for LLMSQL agentic GRPO on verl.

set -euo pipefail

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export MODEL_ATTN_IMPLEMENTATION="${MODEL_ATTN_IMPLEMENTATION:-eager}"
export NGPUS_PER_NODE="${NGPUS_PER_NODE:-1}"

export DATA_DIR="${DATA_DIR:-/root/shared-nvme/rlvr/verl_data/llmsql_agent_0shot_tiny}"
export VAL_FILE="${VAL_FILE:-${DATA_DIR}/val.parquet}"
export EXPERIMENT_NAME="${EXPERIMENT_NAME:-qwen25_coder_3b_agentic_single4090_smoke}"
export LOGGER_BACKENDS="${LOGGER_BACKENDS:-[\"console\"]}"

export LORA_RANK="${LORA_RANK:-0}"
export LORA_ALPHA="${LORA_ALPHA:-64}"

export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-1}"
export PPO_MINI_BATCH_SIZE="${PPO_MINI_BATCH_SIZE:-1}"
export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-512}"
export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-96}"
export PPO_MAX_TOKEN_LEN_PER_GPU="${PPO_MAX_TOKEN_LEN_PER_GPU:-512}"

export ROLLOUT_N="${ROLLOUT_N:-1}"
export ROLLOUT_GPU_MEM_UTIL="${ROLLOUT_GPU_MEM_UTIL:-0.28}"
export ROLLOUT_MAX_MODEL_LEN="${ROLLOUT_MAX_MODEL_LEN:-640}"
export ROLLOUT_MAX_NUM_BATCHED_TOKENS="${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-512}"
export ROLLOUT_MAX_NUM_SEQS="${ROLLOUT_MAX_NUM_SEQS:-1}"
export AGENT_NUM_WORKERS="${AGENT_NUM_WORKERS:-1}"
export ROLLOUT_LAYERED_SUMMON="${ROLLOUT_LAYERED_SUMMON:-false}"
export ROLLOUT_ENFORCE_EAGER="${ROLLOUT_ENFORCE_EAGER:-true}"
export ROLLOUT_FREE_CACHE_ENGINE="${ROLLOUT_FREE_CACHE_ENGINE:-true}"
export ROLLOUT_ENABLE_SLEEP_MODE="${ROLLOUT_ENABLE_SLEEP_MODE:-true}"

export TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-1}"
export SAVE_FREQ="${SAVE_FREQ:-100000}"
export TEST_FREQ="${TEST_FREQ:--1}"
export REWARD_NUM_WORKERS="${REWARD_NUM_WORKERS:-1}"

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

exec "${SCRIPT_DIR}/run_llmsql_grpo_agentic.sh" "$@"
